primero-ci:
  build: .
  ports:
   - "8080:8080"
  volumes:
   - $JENKINS_HOME:$JENKINS_HOME
   - /var/run/docker.sock:/var/run/docker.sock:ro
   - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose:ro
